language: rust
sudo: required

rust:
  - stable
  - beta
  - nightly

os:
  - linux

cache: cargo

env:
  matrix:
    - FEATURE=netlib
    - FEATURE=openblas

matrix:
  allow-failures:
    - rust: nightly

script:
  - cargo test -vv --no-default-features --features=$FEATURE

addons:
  apt:
    sources:
      - kubuntu-backports

    packages:
      - cmake
      - gfortran
