[package]
name = "rula"
version = "0.1.3"
authors = ["Mason Smith <masonium@gmail.com>"]

description = "Linear Algebra package with rust-ndarray interface"

readme = "README.md"

license = "MIT"
keywords = ["linear algebra", "ndarray", "matrix", "vector"]

[features]
default = ["openblas"]
openblas = ["blas/openblas", "lapack/openblas"]
netlib = ["blas/netlib", "lapack/netlib"]

[dependencies]
ndarray = "0.6"
num-traits = "*"

[dependencies.lapack]
version = "0.11"
default-features = false

[dependencies.blas]
version = "0.15"
default-features = false
